### ISSUE TITLE
Backport: Everything up to April

### ISSUE THREAD

**Issue by NetSysFire** [Cataclysm-TLG/Cataclysm-TLG#123]
- [x] 71135 - Luthier tools and woodworked instrument recipes || Comment: None - Backported in #125
- [x] 71889 Fixes power grid teleportation, crashes, and other buggy interactions - Backported in #227
- [x] 71961 - Item faults - Backported in #146
- [x] 71967 - Add book colors in help text || Comment: None - Backported in #126
- [x] 72021 - NPCs use their indoor voices when not in danger || Comment: None - Backported in #126
- [x] 72060 muzzle mods - Backported in #95
- [x] 72063 lixa update - Backported in #101
- [x] 72072 npc move update - Backported in #102
- [x] 72090 fixed limb string extractors - Backported in #105
- [x] 72092 sublimb armor fix - Backported in #106
- [x] 72099 no stam cost on butchery - Backported in #120
- [x] 72106 - Port some mutation/cbm specific fields to enchantments, part 2 || Comment: None
- [x] 72106 port mutation/item stuff to enchantments. - Backported in #149
- [x] 72114 xl/xs prefixes to json - Backported in #110.
- [x] 72120 jmath: don't allow shadowing of built-in functions
- [x] 72140 - Remove the requirement to link with clangTidy || Comment: is that something we even use? - Backported in #127
- [x] 72142 faults can modify price - Backported in #147
- [x] 72145 - Made tinymap load take a tripoint_abs_omt parameter instead of untyped tripoint || Comment: None - Backported in #127
- [x] 72151 mapgen fix - Backported in #111
- [x] 72164 mapgen palette update - Backported in #112
- [x] 72167 - (Fix for tests) Assign valid IDs to NPCs used during testing || Comment: None - Backported in #128
- [x] 72173 - Port some mutation/cbm specific fields to enchantments, part 3 || Comment: None - Backported in #176
- [x] 72174 neoprene patch fix - Backported in #113
- [x] 72175 tool fixes - Backported in #114
- [x] 72177 paper wrapper is tinder - Backported in #115
- [x] 72178  higher "parasites" actually means lower chance of parasites - Backported in #121
- [x] 72194 item group bdays - Backported in #116
- [x] 72196 Added 3-finger gestures to Android - Backported in #137
- [x] 72199 - fix birdshot ammo in beanbag can || Comment: None - Backported in #126
- [x] 72199 REVIEW: fix ammo cans - I had some issues with this when I was removing items from obsoletion, this may not port over easily.
- [x] 72201 fix crafting item preferences - Backported in #117
- [x] 72202 item name in crafting menu fix - Backported in #118
- [x] 72206 More mapgen fixes - Backported in #122
- [x] 72207 - Fix MSVC release build translations compilation || Comment: can someone confirm we need this? compilers aren't my thing - Backported in #127
- [x] 72220 - Add a check for duplicate recipe_ids on load || Comment: None - Backported in #127
- [x] 72224 - Cannibalism checks as a vitamin || Comment: Will probably have a lot of merge conflicts - Backported in #182
- [x] 72227 - make amigara death drop stuff near the character || Comment: None - Backported in #126
- [x] 72230 - Summoned Creature Kill Credit || Comment: None - Backported in #127
- [x] 72233 - Integratedify Feathers || Comment: None - Backported in #127
- [x] 72234 - Refactor camp hunting function || Comment: None - Backported in #136
- [x] 72237 Bugfix for the above, backport both at once #148
- [x] 72243 - Fungal enemies should not be able to revive || Comment: None - Backported in #135
- [x] 72246 - Removed Bore mod location from guns that don't use it, standar-ished mechanism slots to 2. || Comment: Will probably also have a lot of merge conflicts due to 54 files changed - Backported in #183
- [x] 72247 - Fix mutant child's description || Comment: None - Backported in #135
- [x] 72255 bugfix for above - Backported in #150
- [x] 72258 - Make creature's "moves" a protected variable || Comment: I will need to compile and test this on my machine as I am certain we have hardcoded stuff they don't which will run afoul of some of these changes - Backported in #184
- [x] 72282 - Stop eating butternuts with shell || Comment: None - Backported in #135
- [x] 72284 - Adjust pony wall construction || Comment: None - Backported in #135
- [x] 72287 - Remove smartphone from urban samurai || Comment: None - Backported in #135
- [x] 72292 - Fix brush wash action || Comment: None - Backported in #135
- [x] 72293 - Speed up ledge FoV processing || Comment: None - Backported in #138
- [x] 72294 - Remove temperature from butternuts || Comment: None - Backported in #135
- [x] 72295 - Fix several issues of gun_info || Comment: Dependency: 72246 - Backported in #185
- [x] 72300 - Unwield bionic weapons before wielding other weapons or acting a holster || Comment: None - Backported in #138
- [x] 72305 - Set proper overmap terrain for innawoods cave specials || Comment: None - Backported in #138
- [x] 72308 - fix: use root floor above root doors || Comment: None - Backported in #138
- [x] 72311 - Audit: Farming Vehicles + Forklift || Comment: None - Backported in #144
- [x] 72324 - refine calculations of WEAKNESS_TO_WATER || Comment: we aren't using MSC but that trait may be useful eventually - Backported in #176
- [x] 72327 - Item groups can define crafted components for an item || Comment: needs https://github.com/CleverRaven/Cataclysm-DDA/pull/72458 and I think https://github.com/CleverRaven/Cataclysm-DDA/pull/72361 as well they're bugfixes for it - Backported in #186
- [x] 72328 - Enchantments forever || Comment: None - Backported in #189
- [x] 72344 - Add a screen reader mode option and implement on character creation screens || Comment: None - Backported in #191
- [x] 72350 - Adds NUTRIENT_OVERRIDE flag to sunflower seeds || Comment: None - Backported in #138
- [x] 72356 - Add "strictly_unarmed" to buff_taekwondo_static2 || Comment: None - Backported in #138
- [x] 72357 - add 5gal bucket || Comment: None - Backported in #157
- [x] 72366 - fix fatigue restoration decrease || Comment: bugfix for previous enchantment/cbm/mutation stuff - Backported in #192
- [x] 72367 - Give appropriate `examine_action`s to furniture and terrain || Comment: None - Backported in #144
- [x] 72368 - Relocate Russell at New England church retreat || Comment: None - Backported in #144
- [x] 72369 - Bad density || Comment: None - Backported in #144
- [x] 72375 - Crutches melee balance || Comment: None - Backported in #144
- [x] 72378 - Alcohol wipes density fix || Comment: None - Backported in #144
- [x] 72390 - Fix two issues of NPCs sleeping || Comment: None - Backported in #160
- [x] 72403 - Fix NPC guard's decision to pulp corpses || Comment: None - Backported in #160
- [x] 72406 - Limbify drying rate again || Comment: None - Backported in #193
- [x] 72417 - Fix invalidation of soft container nested in a holster || Comment: None - Backported in #161
- [x] 72425 - `var_val` bugfix || Comment: None - Backported in #160
- [x] 72431 - Rural road refactor || Comment: None - Backported in #163
- [x] 72433 - include nornagon's json-ls extension for vscode || Comment: None - Backported in #163
- [x] 72437 - Fix refugee's teamster dialogue which doesn't roll directions anymore || Comment: ~~this might already be fixed~~ - I made some changes here when removingexodii - Backported in #165
- [x] 72445 - Fix JSON corpse harvests and dissection proficiencies || Comment: None - Backported in #167
- [x] 72448 - Autodrivable meadow || Comment: None - Backported in #163
- [x] 72456 - No crafting while driving || Comment: None - Backported in #167
- [x] 72459 - Update EFFECT_ON_CONDITION.md || Comment: None - Backported in #163
- [x] 72468 - Fix seg fault || Comment: some c++ here that worm has worked on since the fork, so she will need to do this
- [x] 72469 - Various fixes for bypassing NO_UNLOAD/NO_RELOAD || Comment: Has conflicts - Backported in #220
- [x] 72471 - Change remote vehicle controller recipe to be consistent || Comment: None - Backported in #167
- [x] 72475 - Fix the NPC's panic underflow || Comment: None - Backported in #167
- [x] 72488 - Fix sugar || Comment: None - Backported in #167
- [x] 72491 - Dead NPCs give samples when dissected || Comment: None - Backported in #167
- [x] 72494 - Update candy in ice cream || Comment: None - Backported in #167
- [x] 72513 - Typifying 'generate' operation for map and tinymap || Comment: None - Backported in #168
- [x] 72519 - Smoke no longer bypasses "NO_BREATHE" flag || Comment: None - Backported in #169
- [x] 72521 - Unhardcode RM13 use actions || Comment: None - Backported in #170
- [x] 72522 - Don't spuriously error when reloading a save after some json errors. || Comment: None - Backported in #170
- [x] 72528 - EOC expansion: 'time_until' function || Comment: None - Backported in #170
- [x] 72537 - Port some bionic to json || Comment: None - Backported in #212
- [x] 72538 - enchantify stat and speed penalties from pain || Comment: note: There's no problem merging this, but Worm may want to fiddle with the numbers after - Backported in #212
- [x] 72540 - Minor LIXA mapgen adjustment || Comment: None - Backported #169
- [x] 72542 - Rebuild all vision transparency cache instead of only one zlevel || Comment: None - Backported in #170
- [x] 72549 - fix range of local coordinates in docs || Comment: None - Backported in #169
- [x] 72556 - Prototypes can fill tanks with items that aren't ammo || Comment: None - Backported in #170
- [x] 72560 - Conditional z level check for nests || Comment: None - Backported in #170
- [x] 72563 - Fix other places that needed to manually clear deferred json. || Comment: None - Backported in #170
- [x] 72564 - Don't check always-assigned integer (interpreted as bool) || Comment: None - Backported in #170
- [x] 72565 - Refactor overmap test so it can run repeatedly in the same area. || Comment: None - Backported in #170
- [x] 72567 - Letting Kukris touch (cut) grass  || Comment: None - Backported in #169
- [x] 72568 - Treat scrolling as arrow key in keybindings list || Comment: thank you lord jesus i cant believe its really happening - Backported in #170
- [x] 72575 - Fixed railroad track length and price || Comment: None - Backported in #169
- [x] 72576 - Add autolearn to cargo pants || Comment: None - Backported in #169
- [x] 72577 - Add rural church location || Comment: None - Backported in #171
- [x] 72580 - Adding MOVEMENT_EXERTION_MODIFIER as enchantment || Comment: None - Backported in #212
- [x] 72582 - Correct a call of write_var_value || Comment: Has conflicts - Backported in #212
- [x] 72585 - Fix price of nickel powder || Comment: None - Backported in #169
- [x] 72587 - use a single EoC to check disarming || Comment: Has conflicts
- [x] 72589 - make some enchantments work better with percentage || Comment: None - Backported in #212
- [x] 72593 - Fix typo in ballista bolt description || Comment: None - Backported in #169
- [x] 72595 - Add a gun-less variant of mansion safe item group and use it in the resort. || Comment: None - Backported in #175
- [x] 72601 - Tune up some misc oter type spawn ratios || Comment: None
- [x] 72609 - Allow disabling limb conditional flags via effects || Comment: None - Backported in #198
- [x] 72613 - Disable warnings related to ledge when the creature has the "LEVITATION" flag || Comment: None - Backported in #175
- [x] 72624 - Update backup generator recipe_deconstruction.json || Comment: None - Backported in #175
- [x] 72629 - Fix RM13 passives always active bug || Comment: None - Backported in #170
- [x] 72637 - Arsonist should buy Merch at full value || Comment: None - Backported in #175
- [x] 72641 - Brewing density fixes || Comment: None - Backported in #175
- [x] 72650 - Fix flaky drying test || Comment: None - Backported in #194
- [x] 72658 - Fix some uses of part_at() to use precalc positions || Comment: Has conflicts
- [x] 72665 - Move ruined books from abstract.json || Comment: Has conflicts - Backported in #204
- [x] 72669 - Fix shadowcasting for weather with sight_penalty != 1.0 || Comment: None - Backported in #198
- [x] 72680 - Notched plank description update || Comment: None - Backported in #175
- [x] 72686 - Make some newer mutant mammals actually use proper harvestlists || Comment: None - Backported in #206
- [x] 72694 - doc: LOCKABLE_DOOR, DOOR_LOCKING || Comment: None - Backported in #175
- [x] 72702 - Misc LIXA dialogue adjustments || Comment: Has conflicts, requires #211 to be done first.
- [x] 72714 - LIXA: congealed light nerf || Comment: None - Backported in #175
- [x] 72717 - Allow migrating from deleted variants || Comment: Has conflicts - Backported in #220
- [x] 72724 - Get roofs generated for basecamps || Comment: None - Backported in #220
- [x] 72728 - NPCs can develop vitamin diseases || Comment: None - Backported in #201
- [x] 72360 - Sky island jewelry quests difficulty curve adjustment

#### Missed backports:

- [x] 72248 - Set terrain memory cache to dirty when setting terrain - Backported in #238
- [x] 72260 - String update "sand casting mold" to "sandcasting mold" for consistency - Backported in #238
- [x] 72214 - Innawoods Limestone Audit - Backported in #238
- [x] 72256 - add 60L tank recipe based on 100L tank - Backported in #238
- [x] 72299 - reword "show more info" in martial art selection menu || Comment: Do we need the changed keybind? - Backported in #238
- [x] 72209 - Fix recipe_id conflicts in in-repo mods || Comment: Needs only the innawoods change - Backported in #238
- [x] 72297 - Fix volume and weight of cornmeal and dry corn kernels - Backported in #238
- [x] 72346 - Remove nonexistent size from documentation, clarify steam store page word || Comment: Only grab the size removal - Backported in #238
- [x] 72358 - Sky islands - all roads lead to u_prevent_death - Backported in #250
- [x] 72165 - Enhanced debug backpack to carry liquids/gasses, utility use_action || Comment: Remove portal storm use action - Backported in #238
- [x] 72127 - Code clearing window was using global font instead of the font actually passed to draw_window - Backported in #238
- [x] 72416 - Add 'Stretch Fabric' requirement to nomad bodygloves || Comment: Can probably  - Backported in #238not be applied as is but this needs some review if we can apply this to similar armor
- [x] 72462 - Clean up formatting and tweak wording in UI documentation - Backported in #238
- [x] 72627 - fix: change debug hotkey for edit global vars - Backported in #238
- [x] 72502 - Typos fixed - Backported in #238
- [x] 72626 - Brutish amalgamation quickfix - Backported in #238
- [x] 72628 - Correct and improve values and recipes for bullets of the caliber .300 BLK || Comment: Dunno about guns but this looks okay to get?
- [x] 72610 - Improve description of wood crossbow - Backported in #238
- [x] 72722 - Monster faction shenanigans || Comment: Concerns mutant animals - Backported in #238
- [x] 72380 - Napkins also need TINDER flag - Backported in #238
- [x] 72452 - Portable game battery type and charges - Backported in #238
- [x] 72643 - Spellcasting menu - automatically open to favorites tab if player has favorited spells - Backported in #238
- [x] 72557 - Rust Zombie Audit - Backported in #238
- [x] 72615 - Reign in the damage from items dropped from height, with math - Backported in #241
- [x] 72719 - Appease clang-tidy || Comment: Has conflicts, is this applicable? - Backported in #241
- [x] 72731 - Achievements Additions - Backported in #238
- [x] 72718 - EOC temp monsters don't drop items or corpses by default - Backported in #238
- [x] 72677 - Improved task activity feedback slightly - Backported in #238
- [x] 72741 - More specific messages for being unable to use supernatural powers || Comment: Concerns Mind over Matter but since psionics are planned, these would prove useful - Backported in #238
- [x] 72730 - Adds ASCII art to S&W 619 - Backported in #238
- [x] 72273 - Eggplants are veggy - Backported in #238
- [x] 72699 - "rows" is defaulted to just spaces || Comment: Will have conflicts but great infrastructure change - Backported in #242
- [x] 72723 - Lore: update UPS description || Comment: Despite it being "lore", this applies to us, too. - Backported in #238
- [x] 72757 - "gathering sights" should be "gathering sites" || Comment: wtf github bug preventing me from getting the patch?! - Backported in #241
- [x] 72558 - Allows setting fixed special scoped parameters for start locations - Backported in #241
- [x] 72760 - LIXA: update laser pipe breaking description - Backported in #241
- [x] 67047 - Concrete Mixer audit - Backported in #241
- [x] 72783 - Fix food fun reduction test not actually having any reduction - Backported in #241
- [x] 72821 - fix and cleanup few itemgroups - Backported in #241
