### ISSUE TITLE
1.0 Checklist

### ISSUE THREAD

**Issue by worm-girl** [Cataclysm-TLG/Cataclysm-TLG#139]
### Is your feature request related to a problem? Please describe.

Here's what we need for a 1.0 release:

### Solution you would like.

- [x] #62 - Bionic and mutagen availability
- [x] Remove skill rust
- [ ] Implement learning caps and adjust skill training rates
- [ ] Snippet audit
- [ ] Profession/scenario description updates for new lore
- [x] Remove Shadow Lieutenant - Done in #179
- [x] All Hub-01 quests completable
- [x] All Smokes quests completable
- [x] All Old Guard quests completable
- [x] All Isherwood quests completable
- [x] All Tacoma Commune quests completable
- [x] All Godco quests completable
- [x] Remove Liam and Pizzaiolo
- [ ] #47 - Old Lab Issues
- [x] Adjust Point Buy Defaults and Maximums
- [ ] Correct Enchantification issues w/r/t Strength Mutations (HP, body weight, BMI)
- [ ] Audit Point Costs for Traits
- [x] Audit all armor encumbrance
- [x] Remove variant steel weapons
- [x] All stages of faction camp construction and missions are completable
- [x] Implement grappling techniques
- [x] Implement skill checks on foraging
- [x] Fork and update mshockxotto+ for TLG, add armor/new plant sprites, grappling icons
- [x] Correct timing and frequency of addiction symptoms
- [ ] URL set up
- [ ] Set up a code of conduct and CONTRIBUTING.md (the file needs to be named like that or it will not show up as guidelines if you make a new issue)
- [x] Clear out any migration files immediately before release
- [x] Look at issue/PR labels before release
- [x] Deal with old dda documentation in `doc/`
- [x] Fully remove imgui and disable the option for it
