### ISSUE TITLE
Backport: April

### ISSUE THREAD

**Issue by NetSysFire** [Cataclysm-TLG/Cataclysm-TLG#162]
- [x] 72823 - uncooked toaster pastries aren't gross - Backported in #241
- [x] 72642 - Basecamp recipes can specify parameters and om_terrain_match_type || Comment: None - Backported in #215
- [x] 72661 - add map_id condition for EoC || Comment: None - Backported in #226
- [x] 72670 - fix clang tidy error in condition.cpp || Comment: None - Backported in #226
- [x] 72681 - Enchantment tests || Comment: None - Backported in #218
- [x] 72693 - Implement weapon proficiencies in C++ (and improve proficiency xp gain for short training durations) || Comment: None - Backported in #215
- [x] 72725 - Removes all hardcoded overmap_connection_id references || Comment: None - Backported in #215
- [x] 72734 - Enforce mon_ prefix for monster id || Comment: Needs the LIXA stuff from March
- [x] 72766 - Remove extern ter ids || Comment: might have already - Backported in #215
- [x] 72768 - Fix zlib old-style-cast build breakage || Comment: None - Backported in #215
- [x] 72771 - Basic JSON ter/furn migration || Comment: None - Backported in #218
- [x] 72789 - Disallow some guns from turrets based on action || Comment: None - Backported in #218
- [x] 72793 - Random bit of wander code isn't unbiased || Comment: None - Backported in #215
- [x] 72812 - Forest biome terrain oter_id -> oter_type_id || Comment: Has conflicts - Backported in #230
- [x] 72815 - city_sizes restriction for city buildings || Comment: None - Backported in #218
- [x] 72834 - Remove extern furn ids || Comment: Has conflicts - Backported in #220
- [x] 72835 - Fixed removal of tree tops over faction camp logged trees || Comment: None - Backported in ~~#218~~ #231
- [x] 72837 - Bugfix for UPS not charging items with empty integrated batteries || Comment: None - Backported in #215
- [x] 72845 - Unified logging and made it tree top aware || Comment: Has conflicts - Backported in #231
- [x] 72847 - remove rapid from national guard bayonet || Comment: None - Backported in #218
- [x] 72850 - Fixed out of bounds transparency cache access || Comment: ditto - Backported in #226
- [x] 72855 - Add dodge chance enchantment  || Comment: None - Backported in #226
- [x] 72862 - By default, EOCs train proficiencies normally || Comment: None - Backported in #226
- [x] 72863 - Fix missing translation in NPC trade denial reason || Comment: None - Backported in #226
- [x] 72879 - Bypass prereq category check for overlapping mod content || Comment: None - Backported in #226
- [x] 72883 - Fix companions ceasing activities when PC enter Z level || Comment: None - Backported in #226
- [x] 72885 - Limit amount of cut damage glass applies on you || Comment: None - Backported in #226
- [x] 72886 - Allow EOCs to search items by caloric content || Comment: None - Backported in #226
- [x] 72889 - Fix stone sickle weapon category typo || Comment: None - Backported in #226
- [x] 72893 - comprehensive deprecation warning updates || Comment: concerns compiling/github stuff. Seems important but it's not worm's forte so she could use a hand here - Backported in #231
- [x] 72895 - Use 'soldering_standard' for electronic fixes || Comment: None - Backported in #226
- [x] 72900 - Fix ASan error, suppress more checks || Comment: None - Backported in #231
- [x] 72906 - run IWYU for some files || Comment: None - Backported in #231
- [x] 72909 - Fix GitHub Actions Node.js runtime deprecation warning in macOS release build workflow || Comment: None - Backported in #231
- [x] 72912 - Debug option to write file with list of cities located on current overmap || Comment: None - Backported in #231
- [x] 72916 - Bugfix for UPS being effectively always on after first activation || Comment: None - Backported in #231
- [x] 72918 - Don't crash when forest mapgen requests groundcover from a biome with no groundcover || Comment: None - Backported in #230
- [x] 72924 - Improve spell checker tokenization and reporting || Comment: None - Backported in #231
- [x] 72926 - Update the spelling dictionary for #72924 || Comment: None - Backported in #231
- [x] 72927 - Retain hole construction || Comment: None - Backported in #233
- [x] 72929 - Fix cast iron material weirdness || Comment: do we even have scrap cast iron? do not port if not - Backported in #233
- [x] 72931 - A bunch of random item reworks: 12 || Comment: None - Backported in #233
- [x] 72933 - Categorize colander as tool || Comment: None - Backported in #233
- [x] 72941 - Remove bonus damages from .38/7.62x39 guns || Comment: None - Backported in #233
- [x] 72945 - debug_mon -> pseudo_debug_mon || Comment: None - Backported in #233
- [x] 72954 - Cleanup unused stuff in mapgen_functions.cpp || Comment: None - Backported in #231
- [x] 72962 - Fixed collapse_check logic || Comment: None - Backported in #233
- [x] 72975 - Worm Spawn Map Extra || Comment: ! - Backported in #233
- [x] 72997 - Fix attack speed test failures || Comment: None - Backported in #233
- [x] 73005 - Fix grapplers not being able to pull you || Comment: None - Backported in #233
- [x] 73026 - Remove some nonsensical items from school chemistry labs || Comment: None - Backported in #234
- [x] 73041 - Fix segfault-causing error in _characters_nearby || Comment: None - Backported in #233
- [x] 73077 - Add more English names and their translations to Simplified Chinese and Japanese || Comment: None - Backported in #234
- [x] 73080 - killed monster can run EoC directly || Comment: None - Backported in #234
- [x] 73081 - Crops will overgrow/die if not harvested in time || Comment: Has non-trivial conflicts - Backported in #252
- [x] 73093 - Fix include error || Comment: None - Backported in #233
- [x] 73148 - Not to try to unload when bow not loaded. || Comment: None - Backported in #233
- [x] 72901 - Docs and in game typos - Backported in #241
- [x] 73111 - Modify comment in weather.h - Backported in #241
- [x] 73066 - Documentation update in light of #73004 - Backported in #241
- [x] 73151 - Favorite ammo must be on the avatar. - Backported in #241
- [x] 73161 - [Sky Island] Add west bunker room upgrades to possible missions - Backported in #250
- [x] 73043 - Fix shotgun speedloader - Backported in #254
- [x] 72586 - Tell vscode astyle extension where to find astyle config - Backported in #241
- [x] 72570 - Incompatible tools pop out of workstations on use - Backported in #241
- [x] 73161 - [Sky Island] Add west bunker room upgrades to possible missions - Backported in #250
- [x] 73141 - docs: clear up outdated info about grab_strength - Backported in #241
- [x] 73144 - Fix overloaded definition for bungalow22 and incorrect definition for house22 - Backported in #241
- [x] 73107 - Do not count magazine as pocket in the pickup inventory - Backported in #241
- [x] 73117 - Can't see doesn't close the crafting GUI  - Backported in #241
- [x] 73166 - Documentation fixes - Backported in #241
- [x] 73022 - Unhardcode dead vegetation extras || Comment: Has a bizarre error about `data/json/mapgen/map_extras/dead_vegetation.json:59:29: Invalid or misplaced field name "ter_furn_transforms" in JSON data` - it may have an unknown missing backport? This makes absolutely no sense - Backported in #243 - see description.
- [x] 73057 - Pigeon reproduction + Foundations for future bird audit - Backported in #258
- [x] 73032 - extend clothes for lumberjack NPCs - Backported in #258
- [x] 72992 - Properly handle default_clause without text in translation string extractor - Backported in #258
- [x] 73060 - fix mobile sidebar label translation - Backported in #258
- [x] 73088 - delete (empty) src/mission_end.cpp - Backported in #258
- [x] 73169 - Random minor JSON adjustments - Backported in #258
- [x] 73168 - add "Forget all recipes" to debug menu - Backported in #258
- [x] 69765 - Alter overmap generation priorities for various specials - Backported in #258
- [x] 73289 - Add missing period to book description - Backported in #258
- [x] 73277 - Remove charges-min and charges-max || Comment: Maybe do not port, use supplied regex in PR body - Applied in #271
- [x] 73312 - Fix Typos and Punctuation of Techniques - Backported in #258
- [x] 73272 - Added code to restore the terminal state on crash on curses - Backported in #258
- [x] 73318 - missing looks_like - Backported in #258
- [x] 73304 - remove count-min and count-max || Comment: Same as charges-min and charges-max - Applied in #271
- [x] 73232 - Implemented scaffolding + doc - Backported in #258
- [x] 73204 - Edit candles to be slightly more realistic - Backported in #258
- [x] 72995 - Make the game angry if luminance is defined as the default value - Backported in #258
- [x] 73234 - Not to use meat chunks in the smoking rack - Backported in #258
- [x] 73270 - remove rand_charges - Backported in #258
- [x] 73263 - 1L Silver Ingot should have "material" property of silver instead of lead - Backported in #258
- [x] 73257 - Adjust MOLLE pouch prices - Backported in #258
- [x] 72861 - Automatically learn proficiencies on load if XP is greater than required - Backported in #258
- [x] 71934 - Unviable portal life forms - Backported and expanded on in #249
