### ISSUE TITLE
NPC feature checklist

### ISSUE THREAD

**Issue by worm-girl** [Cataclysm-TLG/Cataclysm-TLG#203]
### Is your feature request related to a problem? Please describe.

NPCs need to be able to the following:

- [ ] Go somewhere in the immediate area when the player says to go there.
- [ ] Not retreat if told to stand their ground. Retreating is almost always death because of NPC stupidity.
- [ ] Automatically assist with tasks like lockpicking, speech checks, etc.
- [ ] Sleep in an assigned bed if it's in the immediate area.
- [ ] Accept payment for work (crafting or zone stuff) outside the faction camp system. Ideally they could also take payment from the faction pantry if it is set up and nearby, to help make the systems seamless.
- [x] Allow the player to switch to them at any time.
- [x] Shut the fuck up when trying to pathfind through you to fighg the same zombie you are fighting.
- [ ] Use grappling when it is advantageous to do so.
- [ ] Call for help when attacked if friends are around. This could be disabled in the options dialog.
- [ ] Donate blood.
- [x] Almosr never use things that aren't weapons as weapons.
- [ ] (bandits) spawn way more often.

Some of this could be done in a few minutes, some of it will be pretty major.
